//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventDates = new HashSet<EventDate>();
            this.Messages = new HashSet<Message>();
            this.Pictures = new HashSet<Picture>();
            this.ReviewEvents = new HashSet<ReviewEvent>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdLocation { get; set; }
        public int IdOrganisation { get; set; }
        public Nullable<int> IdTypeEvent { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeEnd { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> Parking { get; set; }
        public Nullable<bool> Smoking { get; set; }
        public bool ThirdPartyTickets { get; set; }
        public string ThirdPartyTicketsWeb { get; set; }
        public bool NoTickets { get; set; }
        public Nullable<int> Interesting { get; set; }
        public Nullable<bool> Featured { get; set; }
        public string WebUrl { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool MoreDayEvent { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual TypeEvent TypeEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDate> EventDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewEvent> ReviewEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
