//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organisation()
        {
            this.Events = new HashSet<Event>();
            this.Pictures = new HashSet<Picture>();
            this.ReviewOrganisations = new HashSet<ReviewOrganisation>();
        }
    
        public int Id { get; set; }
        public int IdTypeOrganisation { get; set; }
        public Nullable<int> IdLocation { get; set; }
        public string Description { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public bool PerDayWorkingHours { get; set; }
        public Nullable<System.DateTime> WorkingHoursStart { get; set; }
        public Nullable<System.DateTime> WorkingHoursEnd { get; set; }
        public Nullable<System.DateTime> WeekWorkingHoursStart { get; set; }
        public Nullable<System.DateTime> WeekWorkingHoursEnd { get; set; }
        public Nullable<System.DateTime> SatWorkingHoursStart { get; set; }
        public Nullable<System.DateTime> SatWorkingHoursEnd { get; set; }
        public Nullable<System.DateTime> SunWorkingHoursStart { get; set; }
        public Nullable<System.DateTime> SunWorkingHoursEnd { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Location Location { get; set; }
        public virtual TypeOrganisation TypeOrganisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewOrganisation> ReviewOrganisations { get; set; }
    }
}
