//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public byte[] FileBinary { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public Nullable<int> IdOrganisation { get; set; }
        public Nullable<int> Length { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
