//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewEvent
    {
        public int Id { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Comment { get; set; }
        public int IdEvent { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
