//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReservation
    {
        public int Id { get; set; }
        public int IdTicket { get; set; }
        public int IdCreditCard { get; set; }
        public int Quantity { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
